### PR TITLE
svo_triples generated from pep/20q and association data

### LINKED ISSUE #67: Statistical Analysis of Association Data
Look at correlation between association data an plausibility.

### PR DESCRIPTION
**Pull request by sebastian9991**

### CODE REVIEW

**Comment by sebastian9991** [comment]
generate_selection_assocation script spliits to train and test. Would you prefer these combined?

**Comment by Jacob-Chmura** [comment]
> generate_selection_assocation script spliits to train and test. Would you prefer these combined?

I think it makes sense to keep the splits for our dataset generation. On the other hand, in our separate analytics script, we can simply load both train and test as I have done with the property dataset:

https://github.com/Jacob-Chmura/plausibility-vaccine/blob/cb2755fc451b7b1614c858bfed76de2755bfb05c/scripts/run_property_plausibility_mutual_info.py#L40-L46

**Comment by Jacob-Chmura** [comment]
> > generate_selection_assocation script spliits to train and test. Would you prefer these combined?
> 
> I think it makes sense to keep the splits for our dataset generation. On the other hand, in our separate analytics script, we can simply load both train and test as I have done with the property dataset:
> 
> https://github.com/Jacob-Chmura/plausibility-vaccine/blob/cb2755fc451b7b1614c858bfed76de2755bfb05c/scripts/run_property_plausibility_mutual_info.py#L40-L46

Nevermind, I see what you are saying now, I can handle this

**Comment by Jacob-Chmura** [comment]
> > > generate_selection_assocation script spliits to train and test. Would you prefer these combined?
> > 
> > 
> > I think it makes sense to keep the splits for our dataset generation. On the other hand, in our separate analytics script, we can simply load both train and test as I have done with the property dataset:
> > https://github.com/Jacob-Chmura/plausibility-vaccine/blob/cb2755fc451b7b1614c858bfed76de2755bfb05c/scripts/run_property_plausibility_mutual_info.py#L40-L46
> 
> Nevermind, I see what you are saying now, I can handle this

I ended up just making minor modifications to `generate_selection_association` that enables us to easily just retrieve the scores without creating any intermediate files or additional scripts

**Pull request merged**
